- name: Set Config facts
  ansible.builtin.set_fact:
    vault_aws_region: "{{ lookup('community.hashi_vault.hashi_vault','kv/vault-config:kms-region' ~ vault_conn_string) }}"
    vault_aws_key: "{{ lookup('community.hashi_vault.hashi_vault','kv/vault-config:aws-access-key' ~ vault_conn_string) }}"
    vault_aws_secret: "{{ lookup('community.hashi_vault.hashi_vault','kv/vault-config:aws-secret-key' ~ vault_conn_string) }}"
    vault_kms_key_id: "{{ lookup('community.hashi_vault.hashi_vault','kv/vault-config:kms-key-id' ~ vault_conn_string) }}"
  no_log: true

- name: Install Vault package
  ansible.builtin.package:
    name: vault
    state: present
  become: yes

- name: Create environment file for AWS credentials
  ansible.builtin.template:
    src: vault.env.j2
    dest: /etc/systemd/system/vault.env
    owner: root
    group: root
    mode: '0600'
  become: yes

- name: Add environment file to Vault service
  community.general.ini_file:
    path: /usr/lib/systemd/system/vault.service
    section: Service
    option: EnvironmentFile
    value: /etc/systemd/system/vault.env
    no_extra_spaces: yes
    mode: '0600'
  become: yes

- name: Write Vault configuration
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0644'
  become: yes
  notify:
    - Enable and restart Vault
