- name: Set DPKG architecture
  ansible.builtin.set_fact:
    dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  when: ansible_os_family == 'Debian'

- name: Set dependencies for Ubuntu systems
  ansible.builtin.set_fact:
    dependencies:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies for Docker
  ansible.builtin.package:
    name: "{{ dependencies }}"
    state: present
  become: yes

- name: Import Docker GPG key on Ubuntu systems
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker repository into sources list on Ubuntu
  ansible.builtin.apt_repository:
    repo: |
      deb [arch={{ dpkg_arch }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }} stable
    update_cache: yes
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Set packages for Ubuntu systems
  ansible.builtin.set_fact:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  when: ansible_distribution == 'Ubuntu'

- name: Install packages for Docker
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Ensure Docker is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: yes
